version: "3.5"

services:
  data_anonymization_tool:
    container_name: data_anonymization_tool
    image: nextbrain/data_anonymization_tool:v0.0.3
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8501:8501
