version: "3.5"

services:
  nb_anonymizer:
    container_name: nb_anonymizer
    image: nextbrain/nb_anonymizer:v0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 80
