version: "3.5"

services:
  nb_anonymizer:
    container_name: nb_anonymizer
    image: nextbrain/nb_anonymizer:v0.0.2
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8501:80
    volumes:
      - ./.streamlit/docker:/app/.streamlit
